before_script:
  - virtualenv --quiet --python=python3 .
  - source bin/activate
  - pip install mkdocs
  - pip install mkdocs-material
  - pip install mkdocs-with-pdf
  - pip install mkdocs-pdf-export-plugin
  - pip install mkdocs-git-revision-date-localized-plugin
  - pip install mkdocs-git-authors-plugin
  - mkdocs build --site-dir public

test:
  tags:
    - base
  stage: test
  script:
  - mkdocs build --strict --verbose --site-dir test
  artifacts:
    paths:
    - test
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  tags:
    - base
  stage: deploy
  script:
  - mkdocs build --strict --verbose
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
