before_script:
  - virtualenv --quiet --python=python3 .
  - source bin/activate
  - pip install -r requirements.txt

test:
  tags:
    - base
  stage: test
  script:
  - mkdocs build --clean --strict --site-dir test
  artifacts:
    paths:
    - test
    expire_in: 5 mins
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  tags:
    - base
  stage: deploy
  script:
  - mkdocs build --strict --site-dir public
  artifacts:
    paths:
    - public
    expire_in: 5 mins
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
