before_script:
  - virtualenv --quiet --python=python3 .
  - source bin/activate
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt

test:
  tags:
    - base
  stage: test
  script:
  - mkdocs build --strict --verbose --site-dir test
  artifacts:
    paths:
    - test
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  tags:
    - base
  stage: deploy
  script:
  - mkdocs build --strict --verbose --site-dir deploy
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
