site_name: Portal OpenPyme
repo_name: Portal_OpenPyme_V2.0
repo_url: https://gitlab.openpyme.mx/pyerp/portal_openpyme


theme:
  language: es
  name: material
  logo: img_index/Logo Blanco.png
  favicon: img_index/icon-logo.png
  icon:
    repo: fontawesome/brands/gitlab

  # navigation bar
  features:
    - navigation.tabs
    - navigation.top
    - search.share

  palette:

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-3
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-5
        name: Switch to light mode

  custom_dir: docs/overrides

# menu
nav:
  - Inicio: index.md

  - Manual de usuario:
    - Introducción: manual_usuario/indexManualUsuario.md
    - Administración de cadenas de suministro:
      - Gestión de almacenes: manual_usuario/administracion_cadena_suministros/gestion_almacenes/docs/gestionAlmacenes.md
      - Gestión de compras: manual_usuario/administracion_cadena_suministros/gestion_compras/docs/gestionCompras.md
      - Gestión de costos: manual_usuario/administracion_cadena_suministros/gestion_costos/docs/gestionCostos.md
  
  - Conocimientos técnicos: conocimientos_tecnicos/indexConocimientosTecnicos.md

  - Operación del servicio (Soporte): operacion_servicio/indexOperacionServicio.md

  - Handbook:
    - Mkdocs:
      - Instalación de Mkdocs: handbook/mkdocs/instalacion_Mkdocs/docs/instalacionMkdocs.md
      - Configuración: handbook/mkdocs/configuracion_mkdocs/docs/configuracionMkdocs.md
      - Usos: handbook/mkdocs/uso_mkdocs/docs/usoMkdocs.md
    - GitLab: handbook/gitlab/instalacion_gitlab/docs/instalacionGitlab.md
     
    - Instalación local del Portal OpenPyme: handbook/mkdocs/instalacion_Mkdocs/docs/localPortalOpen.md    
     
  - Preguntas frecuentes: preguntas_frecuentes/indexPreguntasFrecuentes.md


extra:
  generator: false

  social:
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.openpyme.mx/pyerp/portal_openpyme
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/Openpyme
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/openpyme/mycompany


plugins:
  - search
  - git-authors:
      exclude:
        - index.md
  - git-revision-date-localized:
      enable_creation_date: true


extra_css:
  - stylesheets/extra.css


copyright: Copyright &copy; 2022 OpenPyme
